### PR TITLE
Django 1.4 compatibility

### PR DESCRIPTION
**Pull request by jvamvas**
As a long-term support release of Django, version 1.4 is still widely used (extended support ends on October 1, 2015). It would be nice if django-watson would support those projects.

Making use of the [django-compat](https://github.com/arteria/django-compat) package, we can re-route all import statements that would otherwise fail on Django 1.4. This allows us to achieve backwards compatibility with minimal code changes.

### CODE REVIEW

**Comment by etianen** [comment]
Thanks for the pull request! :)

However, I'm not sure that complicating the code base and adding an external dependency is worth it to provide compatibility with a django release that will end long term support in 15 days!

**Comment by philippeowagner** [comment]
@etianen adding [django-compat](https://github.com/arteria/django-compat) would also help to handle for- and backward compatibility in the future. Our main issue is that we are still in the process of upgrading client projects from 1.4.x to 1.8.x - and I know that we are not the only one ;-)

**Comment by etianen** [comment]
I'm still not convinced. Django has made the decision to deprecate and
eventually remove parts of its codebase to maintain long term readability
and prevent bloat. Moving all of this removed code into a "compat" package
just recreates the problem they're looking to solve. What's to stop
django-compat just growing and growing? If deprecation by the core team
isn't a reason to drop a feature, what is?

**Comment by philippeowagner** [comment]
Good points about deprecation. The idea behind django-compat is not to bypass it at all. 

* Be able to use the LTS versions of Django and support newer versions in your app
* Use features from newer Django versions in an old one
* Manage and master the gap between different framework versions

The most things in compat are methods that were moved around in the framework and still does the same thing. A [lot of projects have a compat.py](https://github.com/arteria/django-compat#compatpy) file or compat code and these bits of code are not DRY - especially when looking beyond the app "border". 

Anyway, it was a proposal.

**Comment by michaelkuty** [comment]
When i thihnking about this topic, i'm sad because these things happens in every framework and making something like django-compat is good idea but, making compatibility to this library is bad idea, if you want you can create fork and make this happens, but easiest way is migrating your django project to latest LTS instead of creating useless backward compatibility layer

**Comment by etianen** [comment]
Thanks to everyone for your opinions here! Github is a great place to be. :)

**Pull request closed without merging**
