### PR TITLE
`url` -> `re_path`

### PR DESCRIPTION
**Pull request by Shybert**
Required for Django 4 compatibility. Seems to be the only required change

### CODE REVIEW

**Comment by etianen** [comment]
Thanks for this!

It looks like some of the builds are failing. Maybe you could take a look?

**Comment by Shybert** [comment]
I'll try to figure it out 👍

**Comment by Shybert** [comment]
Seems like the problem was that Django 4 drops compatibility for Python 3.6 and Python 3.7

**Comment by etianen** [comment]
Ah, I think you need to quote 3.10 as a string. The tests seem to be interpretting it as 3.1. :(

Sorry for the lack of response on this. I've started a new job and have been extremely busy!

**Comment by Shybert** [comment]
Everything should hopefully work now. And no worries, I fully understand a busy schedule!

**Comment by etianen** [comment]
Merged! Many thanks.

**Pull request merged**
