### PR TITLE
fixes #104 translation errors when using buildwatson

### LINKED ISSUE #104: The management command buildwatson fails when not setting the current language actively.
We are using [this translation method suggested by the guys from Divio](https://gist.github.com/stefanfoulis/5464012)  to provide translation to the [django SHOP](https://github.com/divio/django-shop). 

I registered the ``LanguageFieldProxy`` fields using this:

    if 'watson' in settings.INSTALLED_APPS:
        import watson
        extra_trans_fields = tuple()
        for i in Product.TRANSLATED_FIELDS: # eg. name_de, name_fr, name_en
            for l in Product.TRANSLATED_LANGUAGES:  # eg. de, fr, en
                extra_trans_fields += ("%s_%s" % (i,l),)
        watson.register(Product, fields=extra_trans_fields) 

Everything works well as expected, but when running the management command ``buildwatson`` I got the following error:

    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/here-n-there/www/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
        utility.execute()
      File "/here-n-there/www/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/here-n-there/www/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/here-n-there/www/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
        output = self.handle(*args, **options)
      File "/here-n-there/www/lib/python2.7/site-packages/django/db/transaction.py", line 224, in inner
        return func(*args, **kwargs)
      File "/here-n-there/www/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 117, in handle
        refreshed_model_count += rebuild_index_for_model(model, engine_slug, verbosity)
      File "/here-n-there/www/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 50, in rebuild_index_for_model
        _bulk_save_search_entries(iter_search_entries())
      File "/here-n-there/www/lib/python2.7/site-packages/watson/registration.py", line 168, in _bulk_save_search_entries
        search_entry_batch = list(islice(search_entries, 0, batch_size))
      File "/here-n-there/www/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 35, in iter_search_entries
        for search_entry in search_engine_._update_obj_index_iter(obj):
      File "/here-n-there/www/lib/python2.7/site-packages/watson/registration.py", line 414, in _update_obj_index_iter
        "title": adapter.get_title(obj),
      File "/here-n-there/www/lib/python2.7/site-packages/watson/registration.py", line 92, in get_title
        return force_text(obj)
      File "/here-n-there/www/lib/python2.7/site-packages/django/utils/encoding.py", line 71, in force_unicode
        s = unicode(s)
    TypeError: coercing to Unicode: need string or buffer, NoneType found

This could be fixed by explicitly activating the language defined in the settings using ``LANGUAGE_CODE``.

### PR DESCRIPTION
**Pull request by philippeowagner**
Problem definition in issue #104

### CODE REVIEW

**Comment by etianen** [comment]
Thanks for the bug report, and for the fast pull request! Looks great!

**Comment by philippeowagner** [comment]
Is it possible to push a release to PyPI?

**Comment by etianen** [comment]
Done! 1.1.6 is out.

**Comment by philippeowagner** [comment]
:+1: Thanks!

**Pull request merged**
