### PR TITLE
Django 1.11 support

### LINKED ISSUE #194: RemovedInDjango110Warning: render() must be called with a dict, not a RequestContext.
Hi,

The `search_results` and `search_result_item` template tags use the context to call `render_to_string`, which would prefer a dict instead of a RequestContext ...

It's possible to call `context.flatten()` to get a dict.

Thanks !

### PR DESCRIPTION
**Pull request by moggers87**
Django 1.11 support

Fixes #194

Only required a couple of small, backwards compatible changes.

### CODE REVIEW

**Comment by etianen** [comment]
I'm away on holiday right now, but it looks like the build broke. Can you
investigate?

**Comment by moggers87** [comment]
Yeah, will do.

**Comment by moggers87** [comment]
OK, not sure I understand the tox setup you've got here - if I tell travis that it's a Python 3.5 env, then I can't use Python 3.6 and vice versa. Yet Python 3.4 is always available?

**Comment by etianen** [comment]
Thanks for the pull request!

I've merged, and hopefully fixed the tox issues in master.

**Pull request merged**
