### PR TITLE
added logic and view for pagination of search results

### PR DESCRIPTION
**Pull request by crackjack**
based on paginate_by of kwargs in urls.py

### CODE REVIEW

**Comment by etianen** [comment]
What is the rational for these changes? So far as I can see, it sets the default paginate_by to 10, and makes the template show the paginator.

I don't think that a default paginate_by is a good idea, as it goes against the pattern set by the other Django generic view classes.

**Comment by crackjack** [comment]
so, how do we add pagination?

how does it currently handle it, I was unable to use it properly, due to which I had to make these changes.

**Comment by crackjack** [comment]
so, how do we add pagination?

how does it currently handle it, I was unable to use it properly, due to which I had to make these changes.

**Comment by etianen** [comment]
url(r"^search/", include("watson.urls", namespace="watson”), kwargs={“paginate_by”: 10})

Then override the search templates to display the paginator.

**Comment by crackjack** [comment]
I did that in the first place.

In the search templates, the "search_results" queryset doesn't have paginator object, so how does one use it?

This is my code:
    {% if search_results.paginator.num_pages > 1 %}
        <div class="pagination">
            {% if search_results.has_previous %}
                <a href="?q={{request.GET.q}}&page={{ search_results.previous_page_number }}" class="prev pegi">PREV</a>
            {% endif %}
            <span class="pegi selected">
                Page {{ search_results.number }} of {{ search_results.paginator.num_pages }}
            </span>
            {% if search_results.has_next %}
                <a href="?q={{request.GET.q}}&page={{ search_results.next_page_number }}" class="next pegi">NEXT</a>
            {% endif %}
        </div>
    {% endif %}

**Comment by etianen** [comment]
When you include the search urls, do this:

url(r"^search/", include("watson.urls", namespace="watson”), kwargs={“paginate_by”: 10})

**Comment by crackjack** [comment]
I have already done that, a month back, I guess.
```url(r'^search/', include("watson.urls", namespace="watson"), kwargs={"paginate_by": 10})
```

**Comment by ursomniac** [comment]
Does pagination ONLY work if you use the built-in view?  If so, in order to adjust context, etc. do you just superclass that view and put in custom get_context_data() etc.?    Right now I'm using watson_search in a FormView's form_valid, which returns results perfectly, but they're not paginated.

**Comment by crackjack** [comment]
I tried it a hundred times, maybe. I didn't figure out it might be a problem with working just with built-in views. So, I had to write my own hook for the pagination, which this pull request is actually about. But, I suppose the maintainer has different thoughts which I was not able to comprehend actually.

If you see the files changed in this pull request, you will see what I have done. That may even be helpful in your case to display the pagination.

**Comment by ursomniac** [comment]
I can get the first 10 items using the bare-bones implementation of SearchView, but only if I change the request to a GET (POST throws a 405 error).

Using SearchView as a superclass and then overriding methods, e.g., get_content_data doesn't appear to work correctly.   I'll have to write my own paginator, which is ANNOYING because I can use Django's default pagination for every other view on the site.  While pagination of search results isn't the primary goal of django-watson, it should be a well-integrated feature.

**Comment by etianen** [comment]
I'm afraid I'm still confused about where the pagination isn't working.

If you provide the paginate_by kwarg to the view, it'll provide a paginator
object to the template, which you can use to generate your pagination.

What's not working?

**Pull request closed without merging**
