### PR TITLE
removing patterns import

### PR DESCRIPTION
**Pull request by SimonGreenhill**
urls.py raises the following ImportError on Django 1.10:

```
  File "/Users/simon/files/Projects/language5/env/lib/python2.7/site-packages/watson/urls.py", line 5, in <module>
    from django.conf.urls import url, patterns
ImportError: cannot import name patterns
```

... and `patterns` isn't needed, so this removes the offending import.

Also, I think https://github.com/etianen/django-watson/pull/148 can be closed as outdated/fixed.

### CODE REVIEW

**Comment by SimonGreenhill** [comment]
...while I'm at it, I'll update travis to the latest versions.

**Comment by etianen** [comment]
Thanks for looking into this!

Looks like there still errors from importing patterns in the tests. Could you fix this too? Then I'll merge.

The details are in the failed travis builds, which you should be able to get at from this pull request page.

**Comment by SimonGreenhill** [comment]
Right, that fixes the import error for patterns, but it looks like there's some more issues with Django 1.10. I'll see if I can look into this in the next few days.

**Comment by etianen** [comment]
Much appreciated! I'm stuck on another project at the moment, so happy to
let you take the lead on Django 1.10 compatibility. :)

**Comment by SimonGreenhill** [comment]
Right, think I've got it, but it'd be good to have a look over this as:
(a) I've had to override some settings to get the test cases to work
(b) I've had to change the buildwatson command to use argparse instead of OptionParser -- this may have affected the semantics of the command. I think I've got it the same, but it'd be good for someone else to look over it and make sure.

**Comment by SimonGreenhill** [comment]
... and yep, (b) has caused tests to break on anything not 1.10

**Comment by etianen** [comment]
So, some things that will make life easier:

Move the settings overrides into https://github.com/etianen/django-watson/blob/master/src/tests/runtests.py

Drop Django 1.7 as a test target. No need to support Django 1.7 any more.

**Comment by SimonGreenhill** [comment]
Great, just one failure left -- related to ede900f, I've got a few long flights coming up so will see if I can get  to it after them

**Comment by SimonGreenhill** [comment]
...and all tests pass.

**Comment by etianen** [comment]
Fantastic, thanks!

Sorry I took a while to merge, I was away on holiday. :)

**Comment by etianen** [comment]
Are there any further issues blocking django 1.10 compatibility, or shall I push out a new release?

**Comment by SimonGreenhill** [comment]
No blockers as far as I can see.

**Comment by etianen** [comment]
django-watson 1.2.3 is now out. Thanks for all your contributions!

**Pull request merged**
