### PR TITLE
Adding WATSON_POSTGRES_SEARCH_CONFIG setting

### PR DESCRIPTION
**Pull request by devxplorer**
There is an [issue #180](https://github.com/etianen/django-watson/issues/180), where @robslotboom proposed to create setting entry for postgresql search config.

But he has not created a pull request, so i desided to create it.

### CODE REVIEW

**Comment by etianen** [comment]
Lovely! This should really go in the wiki too.

**Comment by robslotboom** [comment]
Sorry but I have no active repo so I couldn’t create a pull request...

**Comment by etianen** [comment]
@robslotboom - Hey, no worries. It was a good suggestion, and it's now been implemented nicely by @devxplorer. Everyone gets what they want! 😄

**Comment by amureki** [comment]
Good change! @etianen would you mind to release this one? :)

**Comment by etianen** [comment]
v1.3.0 has just hit pypi!

Thanks @amureki and @devxplorer for the pull requests!

**Pull request merged**
