### PR TITLE
Update test matrix

### PR DESCRIPTION
**Pull request by moggers87**
- Test against Django 2.2
- Remove unsupported versions of Django
- Add Python 3.7 to the test matrix
- Fixed mising raw string to satisfy flake8
- Remove test settings required for older versions of Django

### CODE REVIEW

**Comment by moggers87** [comment]
This would be ready for review, except that Watson doesn't work with MySQL 5.7. Previously this issue has been hidden because Travis was running tests on Ubuntu Trusty (which comes with MySQL 5.6). Now we need Ubuntu Xenial for Python 3.7 and MySQL tests are breaking :upside_down_face: 

I'll open an issue about this in a moment.

**Comment by moggers87** [comment]
Closing this PR as I probably won't be getting time to look into it any time soon.

**Comment by etianen** [comment]
Understood, and thanks for the work you did. I'm likewise in a position where I don't have the time to investigate this more fully right now.

**Comment by etianen** [comment]
Fixed in #261

**Pull request closed without merging**
