### PR TITLE
do not use tuple as key

### PR DESCRIPTION
**Pull request by Anton-Shutik**

### CODE REVIEW

**Comment by Anton-Shutik** [comment]
@etianen Can you pls merge this PR and do release ? It just small compatibility fix

Thanks in advance!

**Comment by etianen** [comment]
I'll take a look at this at the start of next week, no worries!

**Comment by Anton-Shutik** [comment]
Oh nice! Let me know if there is something wrong.

Thanks :)

**Comment by Anton-Shutik** [comment]
Just for reference

```
Traceback:
File ".../local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File ".../local/lib/python2.7/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)
File ".../local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  34.             return bound_func(*args, **kwargs)
File ".../local/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)
File ".../local/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  30.                 return func.__get__(self, type(self))(*args2, **kwargs2)
File ".../local/lib/python2.7/site-packages/braces/views/_forms.py" in dispatch
  22.         return super(CsrfExemptMixin, self).dispatch(*args, **kwargs)
File ".../local/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  89.         return handler(request, *args, **kwargs)
File ".../local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  34.             return bound_func(*args, **kwargs)
File ".../local/lib/python2.7/site-packages/django/views/decorators/debug.py" in sensitive_post_parameters_wrapper
  76.             return view(request, *args, **kwargs)
File ".../local/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  30.                 return func.__get__(self, type(self))(*args2, **kwargs2)
File ".../local/lib/python2.7/site-packages/oauth2_provider/views/base.py" in post
  172.         url, headers, body, status = self.create_token_response(request)
File ".../local/lib/python2.7/site-packages/oauth2_provider/views/mixins.py" in create_token_response
  124.         return core.create_token_response(request)
File ".../local/lib/python2.7/site-packages/oauth2_provider/oauth2_backends.py" in create_token_response
  126.                                                                   headers)
File ".../local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py" in wrapper
  64.             return f(endpoint, uri, *args, **kwargs)
File ".../local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/token.py" in create_token_response
  92.             uri, http_method=http_method, body=body, headers=headers)
File ".../local/lib/python2.7/site-packages/oauthlib/common.py" in __init__
  380.         self.headers = CaseInsensitiveDict(encode(headers or {}))
File ".../local/lib/python2.7/site-packages/oauthlib/common.py" in __init__
  334.         self.proxy = dict((k.lower(), k) for k in data)
File ".../local/lib/python2.7/site-packages/oauthlib/common.py" in <genexpr>
  334.         self.proxy = dict((k.lower(), k) for k in data)

Exception Type: AttributeError at /api/o/token/
Exception Value: 'generator' object has no attribute 'lower'
```

**Comment by etianen** [comment]
Thanks for this. I've gone for a slightly tweaked solution take from django-reversion, which includes a check that the middleware wasn't included multiple times. Please take a look at 7642e3645f311872b8a9e77e2fe0d2630015516e and let me know if it works for you.

**Comment by Anton-Shutik** [comment]
@etianen That is great!

Can you also do a release as well ?

Thanks in advance :)

**Comment by etianen** [comment]
Happy to announce 1.1.9!

**Pull request closed without merging**
